### PR TITLE
Add RuNNer fitting and use in MD Notebook

### PR DESCRIPTION
**Pull request by pmrv**
I tried to use the same name for projects with the training data as [this](https://github.com/pyiron/pyiron_potentialfit/pull/21).

Requires the updates from [pyiron_contrib](https://github.com/pyiron/pyiron_contrib/pull/99) and [pyiron-resources](https://github.com/pyiron/pyiron-resources/pull/36), though.

### CODE REVIEW

**Comment by jan-janssen** [comment]
```
Input Notebook:  RuNNerFit.ipynb
240
Output Notebook: RuNNerFit-out.ipynb
241

242
Executing:   0%|          | 0/9 [00:00<?, ?cell/s]Executing notebook with kernel: python3
243

244
Executing:  11%|█         | 1/9 [00:02<00:18,  2.30s/cell]
245
Executing:  67%|██████▋   | 6/9 [00:02<00:00,  3.29cell/s]
246
Executing:  78%|███████▊  | 7/9 [00:03<00:00,  2.24cell/s]
247
Traceback (most recent call last):
248
  File "/usr/share/miniconda/envs/test/bin/papermill", line 10, in <module>
249
    sys.exit(papermill())
250
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/core.py", line 829, in __call__
251
    return self.main(*args, **kwargs)
252
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/core.py", line 782, in main
253
    rv = self.invoke(ctx)
254
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
255
    return ctx.invoke(self.callback, **ctx.params)
256
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/core.py", line 610, in invoke
257
    return callback(*args, **kwargs)
258
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
259
    return f(get_current_context(), *args, **kwargs)
260
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/papermill/cli.py", line 256, in papermill
261
    execution_timeout=execution_timeout,
262
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/papermill/execute.py", line 118, in execute_notebook
263
    raise_for_execution_errors(nb, output_path)
264
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/papermill/execute.py", line 230, in raise_for_execution_errors
265
    raise error
266
papermill.exceptions.PapermillExecutionError: 
267
---------------------------------------------------------------------------
268
Exception encountered at "In [7]":
269
---------------------------------------------------------------------------
270
AttributeError                            Traceback (most recent call last)
271
<ipython-input-7-6c1876cab137> in <module>
272
----> 1 j.add_job_to_fitting(pr_fit.load('df1_A1_A2_A3_EV_elast_phon'))
273

274
/usr/share/miniconda/envs/test/lib/python3.7/site-packages/pyiron_contrib/atomistic/runner/job.py in add_job_to_fitting(self, job)
275
     86             job (:class:`.TrainingContainer`): job to add to database
276
     87         """
277
---> 88         self._training_ids.append(job.id)
278
     89 
279
     90     def write_input(self):
280

281
AttributeError: 'NoneType' object has no attribute 'id'
282

283
Input Notebook:  RuNNerMD.ipynb
284
Output Notebook: RuNNerMD-out.ipynb
285

286
Executing:   0%|          | 0/9 [00:00<?, ?cell/s]Executing notebook with kernel: python3
287

288
Executing:  11%|█         | 1/9 [00:02<00:19,  2.48s/cell]
289
Executing:  44%|████▍     | 4/9 [00:02<00:02,  1.86cell/s]
290
Executing:  44%|████▍     | 4/9 [00:03<00:04,  1.23cell/s]
291
Traceback (most recent call last):
292
  File "/usr/share/miniconda/envs/test/bin/papermill", line 10, in <module>
293
    sys.exit(papermill())
294
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/core.py", line 829, in __call__
295
    return self.main(*args, **kwargs)
296
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/core.py", line 782, in main
297
    rv = self.invoke(ctx)
298
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
299
    return ctx.invoke(self.callback, **ctx.params)
300
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/core.py", line 610, in invoke
301
    return callback(*args, **kwargs)
302
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
303
    return f(get_current_context(), *args, **kwargs)
304
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/papermill/cli.py", line 256, in papermill
305
    execution_timeout=execution_timeout,
306
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/papermill/execute.py", line 118, in execute_notebook
307
    raise_for_execution_errors(nb, output_path)
308
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/papermill/execute.py", line 230, in raise_for_execution_errors
309
    raise error
310
papermill.exceptions.PapermillExecutionError: 
311
---------------------------------------------------------------------------
312
Exception encountered at "In [4]":
313
---------------------------------------------------------------------------
314
ValueError                                Traceback (most recent call last)
315
/usr/share/miniconda/envs/test/lib/python3.7/site-packages/pyiron_base/project/generic.py in __getitem__(self, item)
316
   1386                         item=item_lst[0], convert_to_object=False
317
-> 1387                     ).__getitem__("/".join(item_lst[1:]))
318
   1388                 except ValueError:
319

320
/usr/share/miniconda/envs/test/lib/python3.7/site-packages/pyiron_base/project/generic.py in __getitem__(self, item)
321
   1391                     ).__getitem__("/".join(item_lst[1:]))
322
-> 1392         return self._get_item_helper(item=item, convert_to_object=True)
323
   1393 
324

325
/usr/share/miniconda/envs/test/lib/python3.7/site-packages/pyiron_base/project/generic.py in _get_item_helper(self, item, convert_to_object)
326
   1457             return self.open(item)
327
-> 1458         raise ValueError("Unknown item: {}".format(item))
328
   1459 
329

330
ValueError: Unknown item: runner_fit
331

332
During handling of the above exception, another exception occurred:
333

334
ValueError                                Traceback (most recent call last)
335
<ipython-input-4-c59b86604cc3> in <module>
336
----> 1 j.potential = pr['../runner_fit'].load('fit').lammps_potential
337

338
/usr/share/miniconda/envs/test/lib/python3.7/site-packages/pyiron_base/project/generic.py in __getitem__(self, item)
339
   1389                     return self._get_item_helper(
340
   1390                         item=item_lst[0], convert_to_object=True
341
-> 1391                     ).__getitem__("/".join(item_lst[1:]))
342
   1392         return self._get_item_helper(item=item, convert_to_object=True)
343
   1393 
344

345
/usr/share/miniconda/envs/test/lib/python3.7/site-packages/pyiron_base/project/generic.py in __getitem__(self, item)
346
   1390                         item=item_lst[0], convert_to_object=True
347
   1391                     ).__getitem__("/".join(item_lst[1:]))
348
-> 1392         return self._get_item_helper(item=item, convert_to_object=True)
349
   1393 
350
   1394     def __repr__(self):
351

352
/usr/share/miniconda/envs/test/lib/python3.7/site-packages/pyiron_base/project/generic.py in _get_item_helper(self, item, convert_to_object)
353
   1456         if item in os.listdir(self.path) and os.path.isdir(os.path.join(self.path, item)):
354
   1457             return self.open(item)
355
-> 1458         raise ValueError("Unknown item: {}".format(item))
356
   1459 
357
   1460     def _remove_files(self, pattern="*"):
358

359
ValueError: Unknown item: runner_fit
```

**Comment by pmrv** [comment]
Again, I've used the project name that @sudarsan-surendralal used [here](https://github.com/pyiron/pyiron_potentialfit/pull/21/files), but this project is not created yet with the current notebooks, so both notebooks fail.  Once #21 is merged, I'll rebase it and the notebooks here should work too.

**Comment by sudarsan-surendralal** [comment]
I've merged [this PR](https://github.com/pyiron/pyiron_potentialfit/pull/21) to this branch so hopefully, the tests will work now!

**Comment by jan-janssen** [comment]
```
papermill.exceptions.PapermillExecutionError: 
298
---------------------------------------------------------------------------
299
Exception encountered at "In [7]":
300
---------------------------------------------------------------------------
301
AttributeError                            Traceback (most recent call last)
302
<ipython-input-7-6c1876cab137> in <module>
303
----> 1 j.add_job_to_fitting(pr_fit.load('df1_A1_A2_A3_EV_elast_phon'))
304

305
/usr/share/miniconda/envs/test/lib/python3.7/site-packages/pyiron_contrib/atomistic/runner/job.py in add_job_to_fitting(self, job)
306
     86             job (:class:`.TrainingContainer`): job to add to database
307
     87         """
308
---> 88         self._training_ids.append(job.id)
309
     89 
310
     90     def write_input(self):
311

312
AttributeError: 'NoneType' object has no attribute 'id'
313
```
...
```
363
---------------------------------------------------------------------------
364
Exception encountered at "In [4]":
365
---------------------------------------------------------------------------
366
AttributeError                            Traceback (most recent call last)
367
<ipython-input-4-5b15a2d5f235> in <module>
368
----> 1 j.potential = Project('../day_2/runner_fit').load('fit').lammps_potential
369

370
AttributeError: 'NoneType' object has no attribute 'lammps_potential'
371

372
Input Notebook:  ex_xx_validation.ipynb
373
Output Notebook: ex_xx_validation-out.ipynb
374
```

**Comment by pmrv** [comment]
Working on it.

**Comment by pmrv** [comment]
> Working on it.

I've checked on the cluster now and both notebooks run through.  I didn't catch that @sudarsan-surendralal notebook with the database import only runs on day 3, so I copy the files and import them into a new project.

**Comment by jan-janssen** [comment]
I guess the easiest way for debugging is mybinder [Binder](https://mybinder.org/v2/gh/pyiron/pyiron_potentialfit/runner) as it gives you exactly the environment that is used to execute the tests.

**Pull request merged**
