### PR TITLE
Data intro notebook

### PR DESCRIPTION
**Pull request by yury-lysogorskiy**
- data introduction notebook day2/00-IntroductionDay2.ipynb
- with  day_2/* subfolders by 00-, 01-, ... prefixes
- modify/update day2/ace/pacemaker-fit-tutorial.ipynb

### CODE REVIEW

**Comment by jan-janssen** [comment]
I guess the issue is the renaming of the other notebooks - those seem to be outdated versions.

**Comment by jan-janssen** [comment]
The easiest way is to always have separate pull requests for unrelated changes.

**Comment by jan-janssen** [comment]
```
Traceback (most recent call last):
332
  File "/usr/share/miniconda/envs/test/bin/papermill", line 10, in <module>
333
    sys.exit(papermill())
334
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/core.py", line 829, in __call__
335
    return self.main(*args, **kwargs)
336
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/core.py", line 782, in main
337
    rv = self.invoke(ctx)
338
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
339
    return ctx.invoke(self.callback, **ctx.params)
340
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/core.py", line 610, in invoke
341
    return callback(*args, **kwargs)
342
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
343
    return f(get_current_context(), *args, **kwargs)
344
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/papermill/cli.py", line 256, in papermill
345
    execution_timeout=execution_timeout,
346
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/papermill/execute.py", line 118, in execute_notebook
347
    raise_for_execution_errors(nb, output_path)
348
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/papermill/execute.py", line 230, in raise_for_execution_errors
349
    raise error
350
papermill.exceptions.PapermillExecutionError: 
351
---------------------------------------------------------------------------
352
Exception encountered at "In [4]":
353
---------------------------------------------------------------------------
354
AttributeError                            Traceback (most recent call last)
355
<ipython-input-4-9807130a7c38> in <module>
356
----> 1 j.potential = Project('../day_2/runner/runner_fit').load('fit').lammps_potential
357

358
AttributeError: 'NoneType' object has no attribute 'lammps_potential'
359
```

@yury-lysogorskiy It is more simple, the notebook basically requires the old path `../day_2/runner/runner_fit` so we have to update the notebook.

**Comment by yury-lysogorskiy** [comment]
@jan-janssen Thank you for fixing that!

**Pull request merged**
