### PR TITLE
Add best potentials

### PR DESCRIPTION
**Pull request by jan-janssen**
@mrshrbld and @yury-lysogorskiy please validate that I uploaded the correct potentials. 

@Leimeroth Can you also add you best fit? 

@muh-hassani In the home directory of each user we need a `.pyiron` file which specifies the `resources` folder in the resource path. I added an example `.pyiron` file in the repository, which is currently configured to work with mybinder. 

@sudarsan-surendralal Can you update the examples of day three to use `Cu-runner` and `Cu-ace` for comparison?

### CODE REVIEW

**Comment by jan-janssen** [comment]
In addition I created a small test repository which demonstrates loading the ace and runner potential from the resources: https://github.com/jan-janssen/potential_testing

**Comment by Leimeroth** [comment]
I added a good_potentials directory in the updates branch. I am still changing some stuff, so I didn't merge it yet.

**Comment by jan-janssen** [comment]
@Leimeroth So `DF1residual0.128179.eam.fs` is the best one, right?

**Comment by Leimeroth** [comment]
It is only fitted to the 100 structure dataset, so it should be worse than the others for DF2

**Comment by jan-janssen** [comment]
@Leimeroth So which one should we use for day 3?

**Comment by Leimeroth** [comment]
The best one for the 1000structure dataset should be more transferable, so I would take that one

**Comment by jan-janssen** [comment]
`residual68.2249.eam.fs` ?

**Comment by Leimeroth** [comment]
Yes. But I still would leave the other ones in the directory so that one can see how much worse the potential fitted to 100 structures is when calculating properties of the 1000 structures and the other way around. That is probably a nice example for the transferability of potentials.

**Comment by jan-janssen** [comment]
They still have the potential from day2 for comparison, all I want to do is add a optimal potential for comparison, as the participants most likely do not have the time to run an extensive fit in particular for the machine learning potentials. So I added the optimal potentials to the pyiron resources, then the participants can easily load them by just specifying a sting and the potentials are also listed in `list_potentials()`.

**Pull request merged**
